###############################################################################
# Project:  COCKTAIL training
# Descr:    A simple scanner generated with rex
# Kind:     Makefile
# Author:   Dr. Juergen Vollmer <Juergen.Vollmer@informatik-vollmer.de>
# $Id: Makefile,v 1.5 2007/06/03 16:56:31 vollmer Exp $
###############################################################################

# The executable to produce:
MAIN		= scan

# Source files
SRC_C		= main$(SOLUTION).c
SRC_H		=
SRC		= l$(SOLUTION).rex

# Generated files
GEN_C		= l_scan.c l_scanSource.c
GEN_H		= l_scan.h l_scanSource.h
GEN		=

###############################################################################

include ../config.mk

###############################################################################

# Create your scanner
all: $(MAIN)


# Run the test suite
test:
	./$(MAIN) test1; echo
	./$(MAIN) test2; echo
	./$(MAIN) test3; echo
	./$(MAIN) test4; echo
	./$(MAIN) test5; echo

###############################################################################

# Generate the scanner
l_scan.c: l$(SOLUTION).rex
	rex -cdis -y  l$(SOLUTION).rex
	rm -f l_scanDrv.c

# These files are generated by REX too:
l_scan.h: 	l_scan.c
l_scanSource.c: l_scan.c
l_scanSource.h: l_scan.c

###############################################################################

include ../common.mk

###############################################################################
